site_name: pym2v
site_url: https://bytecaretech.github.io/pym2v
repo_url: https://github.com/bytecaretech/pym2v
theme:
  name: material
  palette:
    primary: deep purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            heading_level: 3
            merge_init_into_class: true
            show_docstring_examples: false
            separate_signature: true

nav:
  - Home: index.md
  - References: references.md
